version: "3"
services:
  backend:
    build: ./backend
    links:
      - db
    ports:
      - "5000:5000"

  frontend:
     build: ./frontend/meal-planner
     ports:
      - "5173:5173"
  
  db:
    image: mysql:latest
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro