version: "3"
services:
  app:
    build: ./backend
    links:
      - db
    ports:
      - "5000:5000"

  db:
    image: mysql:latest
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro